---
- name: make a build dir
  file: state=directory name=/root/gogs-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/gogs-dockerized/Dockerfile

- name: put gogs.rb
  template: src=gogs.rb dest=/root/gogs-dockerized/gogs.rb

- name: put app.ini
  template: src=app.ini dest=/root/gogs-dockerized/app.ini

- name: put gogs.sh
  template: src=gogs.sh dest=/root/gogs-dockerized/gogs.sh mode=0755

- name: build a Docker image for gogs
  command: docker build -t gitinsky/gogs:0.1.0 --rm /root/gogs-dockerized

- name: check if a gogs container is started
  command: bash -c "docker ps | grep gogs"
  ignore_errors: True
  register: result

- name: start a gogs container
  command: docker run -d -p=2222:22 -p=3000:3000 --link mysql:db -v {{ ext_gogs_repo_volume }}:/gogs-repositories -name gogs gitinsky/gogs:0.1.0
  when: result|failed
